name: Expo Review

on:
  push:
    branches:
      - master
      - release/*

jobs:
  publish:
    name: Publish review and build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
      - run: yarn install
      - run: expo build:android --release-channel review -t apk 
        
